[package]
name = "memforks"
version = "0.1.0"
edition = "2024.beta"
license = "Apache-2.0"
authors = ["MemForks contributors"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
memforks = "0x0"

[dev-dependencies]

[dev-addresses]
