#!/usr/bin/env bash
# deploy.sh — idempotent testnet deploy for the MemForks Move package.
#
# Usage:
#   ./scripts/deploy.sh                    # deploy to testnet (default)
#   ./scripts/deploy.sh --network devnet  # override network
#   ./scripts/deploy.sh --upgrade          # upgrade an existing deployment
#
# After a successful deploy the script writes PACKAGE_ID to .deployed.env
# so spike scripts and the SDK can pick it up automatically.
#
# Idempotency: if .deployed.env exists and --upgrade is not passed, the script
# prints the existing package ID and exits 0 — safe to re-run in CI.

set -euo pipefail

NETWORK="${NETWORK:-testnet}"
CONTRACTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/contracts"
DEPLOYED_ENV="$(dirname "${BASH_SOURCE[0]}")/../.deployed.env"
UPGRADE=false

# ─── Parse flags ─────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --network) NETWORK="$2"; shift 2 ;;
    --upgrade) UPGRADE=true;  shift   ;;
    *)         echo "Unknown flag: $1"; exit 1 ;;
  esac
done

# ─── Switch Sui client to target network ─────────────────────────────────────
echo "→ Network: $NETWORK"
sui client switch --env "$NETWORK" 2>/dev/null || true

ACTIVE_ADDR=$(sui client active-address 2>/dev/null | tail -1)
echo "→ Active address: $ACTIVE_ADDR"

# ─── Idempotency check ───────────────────────────────────────────────────────
if [[ -f "$DEPLOYED_ENV" && "$UPGRADE" == "false" ]]; then
  source "$DEPLOYED_ENV"
  echo "✓ Already deployed. Package ID: $MEMFORKS_PACKAGE_ID"
  echo "  Pass --upgrade to re-deploy."
  exit 0
fi

# ─── Build first ─────────────────────────────────────────────────────────────
echo "→ Building Move package..."
sui move build --path "$CONTRACTS_DIR"

# ─── Deploy ──────────────────────────────────────────────────────────────────
echo "→ Publishing to $NETWORK..."

PUBLISH_OUTPUT=$(sui client publish \
  --path "$CONTRACTS_DIR" \
  --gas-budget 200000000 \
  --json 2>&1)

# Extract package ID from JSON output
PACKAGE_ID=$(echo "$PUBLISH_OUTPUT" | \
  python3 -c "
import sys, json
data = json.load(sys.stdin)
for change in data.get('objectChanges', []):
    if change.get('type') == 'published':
        print(change['packageId'])
        break
" 2>/dev/null || echo "")

if [[ -z "$PACKAGE_ID" ]]; then
  echo "✗ Could not extract package ID from publish output:"
  echo "$PUBLISH_OUTPUT"
  exit 1
fi

echo "✓ Published. Package ID: $PACKAGE_ID"

# Extract transaction digest
TX_DIGEST=$(echo "$PUBLISH_OUTPUT" | \
  python3 -c "import sys, json; d=json.load(sys.stdin); print(d.get('digest',''))" 2>/dev/null || echo "")
echo "  Tx digest: $TX_DIGEST"

# ─── Persist ─────────────────────────────────────────────────────────────────
cat > "$DEPLOYED_ENV" <<EOF
# Auto-generated by scripts/deploy.sh — do NOT commit if it contains secrets.
MEMFORKS_PACKAGE_ID=$PACKAGE_ID
MEMFORKS_DEPLOY_NETWORK=$NETWORK
MEMFORKS_DEPLOY_TX=$TX_DIGEST
MEMFORKS_DEPLOY_ADDR=$ACTIVE_ADDR
EOF

echo "✓ Written to .deployed.env"
echo ""
echo "  export MEMFORKS_PACKAGE_ID=$PACKAGE_ID"
